d = {
    'voxel_arr_MRI': 0,
    'voxel_arr_DTI': 0,
    'Init_neuron_model_ready': 0,
    'Init_mesh_ready': 0,
    'Adjusted_neuron_model_ready': 0,
    'CSF_mesh_ready': 0,
    'Adapted_mesh_ready': 0,
    'signal_generation_ready': 0,
    'Parallel_comp_ready': 0,
    'Parallel_comp_interrupted': 0,
    'IFFT_ready': 0,
    'MRI_data_name': 'icbm_avg_152_segmented.nii.gz',
    'MRI_in_m': 0,
    'DTI_data_name': '',
    'DTI_in_m': 0,
    'CSF_index': 1.0,
    'WM_index': 3.0,
    'GM_index': 2.0,
    'default_material': 3,
    'Electrode_type': 'Medtronic3389',
    'Brain_shape_name': '0',
    'Aprox_geometry_center': [10.92957028, -12.11697637, -7.69744601],
    'Approximating_Dimensions': [40.0, 40.0, 40.0],
    'Implantation_coordinate_X': 10.929,
    'Implantation_coordinate_Y': -12.117,
    'Implantation_coordinate_Z': -7.697,
    'Second_coordinate_X': 10.929,
    'Second_coordinate_Y': -9.437,
    'Second_coordinate_Z': 3.697,
    'Rotation_Z': 0.0,
    'encap_thickness': 0.2,
    'encap_tissue_type': 2,
    'encap_scaling_cond': 0.8,
    'encap_scaling_perm': 0.8,
    'pattern_model_name': '0',
    'Axon_Model_Type': 'McIntyre2002',
    'diam_fib': [5.7],
    'n_Ranvier': [21],
    'v_init': -80.0,
    'Neuron_model_array_prepared': 0,
    'Name_prepared_neuron_array': '0',
    'EQS_core': 'QS',
    'Skip_mesh_refinement': 0,
    'el_order': 2,
    'number_of_processors': 0,
    'FEniCS_MPI': 0,
    'current_control': 1,
    'Phi_vector': [0.0015, None, 0.0, None],
    'Solver_Type': 'GMRES',
    'freq': 130.0,
    'T': 60.0,
    't_step': 1.0,
    'phi': 0.0,
    'Signal_type': 'Rectangle',
    'Ampl_scale': 1.0,
    'CPE_activ': 0,
    'Full_Field_IFFT': 0,
    'spectrum_trunc_method': 'High Amplitude Method',
    'trunc_param': 50,
    'Truncate_the_obtained_full_solution': 0,
    'Show_paraview_screenshots': 0,
    }
