# -*- coding: utf-8 -*-
"""
Created on Sun Oct 28 08:34:11 2018

@author: trieu,butenko
"""
import numpy as np

d = {
    'voxel_arr_MRI': 1,
    'voxel_arr_DTI': 0,
    'Init_neuron_model_ready': 0,
    'Init_mesh_ready': 0,
    'Adjusted_neuron_model_ready': 0,
    'CSF_mesh_ready': 0,
    'Adapted_mesh_ready': 0,
    'signal_generation_ready': 0,
    'Parallel_comp_ready': 0,
    'Parallel_comp_interrupted': 0,
    'IFFT_ready': 0,
    'MRI_data_name': 'MRI_Waxholm_complete.txt',
    'MRI_in_m': 0,
    'DTI_data_name': '',
    'DTI_in_m': 0,
    'CSF_index': 1.0,
    'WM_index': 2.0,
    'GM_index': 3.0,
    'default_material': 3,
    'Electrode_type': 'SNEX100',
    'Brain_shape_name': '0',
    'Aprox_geometry_center': [2.1781, -2.6281, -0.7],
    'Approximating_Dimensions': [10.0, 10.0, 10.0],
    'Implantation_coordinate_X': 2.1781,
    'Implantation_coordinate_Y': -2.6281,
    'Implantation_coordinate_Z': -0.7,
    'Second_coordinate_X': 2.1781,
    'Second_coordinate_Y': -2.6281,
    'Second_coordinate_Z': 0.7,
    'Rotation_Z': 0.0,
    'encap_thickness': 0.1,
    'encap_tissue_type': 3,
    'encap_scaling_cond': 0.5,
    'encap_scaling_perm': 1.0,
    'pattern_model_name': 'STN_rat_neuron.csv',
    'Axon_Model_Type': 'McIntyre2002',
    'diam_fib': [2.0],
    'n_Ranvier': [15],
    'v_init': -80.0,
    'Neuron_model_array_prepared': 0,
    'Name_prepared_neuron_array': 'STN_axons_array.csv',
    'EQS_core': 'QS',
    'Skip_mesh_refinement': 1,
    'el_order': 2,
    'number_of_processors': 2,
    'FEniCS_MPI': 0,
    'current_control': 1,
    'Phi_vector': [0.0001, 0.0],
    'Solver_Type': 'GMRES',
    'freq': 130.0,
    'T': 90.0,
    't_step': 10.0,
    'phi': 3500.0,
    'Signal_type': 'Rectangle',
    'Ampl_scale': 1.0,
    'CPE_activ': 0,
    'Full_Field_IFFT': 0,
    'spectrum_trunc_method': 'Octave Band Method',
    'trunc_param': 1000.0,
    'Truncate_the_obtained_full_solution': 0,
    'Show_paraview_screenshots': 0,

    'beta': 0.0,
    'K_A': 0.0,
    'beta_ground': 0.0,
    'K_A_ground': 0.0,
    
    'Global_rot': 0,
    'X_coord_old': [1.6781, 2.1781, 2.6781],
    'Y_coord_old': [-3.1281, -2.6281, -2.1281],
    'Z_coord_old': [-0.2, -0.7, -1.2],
    'YZ_angles': [0.0],
    'ZX_angles': [0.0],
    'XY_angles': [0.0, 90.0],
    
    't_step_end': 1200,
    'VTA_from_divE': 0,
    'VTA_from_NEURON': 0,
    'VTA_from_E': 0,
    'Activation_threshold_VTA': 0,
    
    'refinement_frequency': [520.0],
    'num_ref_freqs': 1,
    'rel_div_CSF': -1,
    'Adaptive_frac_div': 0.175,
    'Min_Scaling': 1.0,
    'CSF_ref_reg': 1.0,
    'rel_div': 12.0,
    'rel_div_current': 0.12,
    }
