# -*- coding: utf-8 -*-
"""
Created on Sun Oct 28 08:34:11 2018

@author: trieu,butenko
"""
import numpy as np

d = {
    'voxel_arr_MRI': 0,
    'voxel_arr_DTI': 0,
    'Init_neuron_model_ready': 0,
    'Init_mesh_ready': 0,
    'Adjusted_neuron_model_ready': 0,
    'CSF_mesh_ready': 0,
    'Adapted_mesh_ready': 0,
    'signal_generation_ready': 0,
    'Parallel_comp_ready': 0,
    'Parallel_comp_interrupted': 0,
    'IFFT_ready': 0,
    'MRI_data_name': 'icbm_avg_152_segmented.nii.gz',
    'MRI_in_m': 0,
    'DTI_data_name': '',
    'DTI_in_m': 0,
    'CSF_index': 1.0,
    'WM_index': 3.0,
    'GM_index': 2.0,
    'default_material': 2,
    'Electrode_type': 'Medtronic3389',
    'Brain_shape_name': '0',
    'Aprox_geometry_center': [11.654, -18.403, 6.845],
    'Approximating_Dimensions': [80.0, 80.0, 80.0],
    'Implantation_coordinate_X': 11.654,
    'Implantation_coordinate_Y': -18.403,
    'Implantation_coordinate_Z': 6.845,
    'Second_coordinate_X': 11.654,
    'Second_coordinate_Y': -18.403,
    'Second_coordinate_Z': 7.845,
    'Rotation_Z': 10.0,
    'encap_thickness': 0.30000000000000004,
    'encap_tissue_type': 3,
    'encap_scaling_cond': 1.0,
    'encap_scaling_perm': 1.0,
    'pattern_model_name': '0',
    'Axon_Model_Type': 'McIntyre2002',
    'diam_fib': [5.7],
    'n_Ranvier': [21],
    'v_init': -80.0,
    'Neuron_model_array_prepared': 0,
    'Name_prepared_neuron_array': '',
    'EQS_core': 'QS',
    'Skip_mesh_refinement': 0,
    'el_order': 2,
    'number_of_processors': 8,
    'FEniCS_MPI': 0,
    'current_control': 1,
    'Phi_vector': [0.001, 0.0, None, None],
    'Solver_Type': 'Default',
    'freq': 130.0,
    'T': 60.0,
    't_step': 1.0,
    'phi': 50.0,
    'Signal_type': 'Rectangle',
    'Ampl_scale': 1.0,
    'CPE_activ': 0,
    'Full_Field_IFFT': 0,
    'spectrum_trunc_method': 'Octave Band Method',
    'trunc_param': 20000.0,
    'Truncate_the_obtained_full_solution': 0,
    'external_grounding': 0,

    'beta': 0.0,
    'K_A': 0.0,
    'beta_ground': 0.0,
    'K_A_ground': 0.0,
    
    'Global_rot': 1,
    'x_seed': 11.654,
    'y_seed': -18.403,
    'z_seed': 11.095,
    'x_steps': 12,
    'y_steps': 0,
    'z_steps': 12,
    'x_step': 0.5,
    'y_step': 0.5,
    'z_step': 0.5,
    'alpha_array_glob': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 90.0],
    'beta_array_glob': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    'gamma_array_glob': [0.0, 30.0, 60.0, 90.0, 120.0, 150.0, 0.0],
    
    't_step_end': 1200,
    'VTA_from_divE': 0,
    'VTA_from_NEURON': 0,
    'VTA_from_E': 0,
    'Activation_threshold_VTA': 0,
    
    'refinement_frequency': [-1],
    'num_ref_freqs': 1,
    'rel_div_CSF': -1,
    'Adaptive_frac_div': 1.0,
    'Min_Scaling': 1.0,
    'CSF_ref_reg': 10.0,
    'rel_div': 24.0,
    'rel_div_current': 1.0,
    }
