name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_test_image:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Build docker `base` image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: sfbelaine/oss_dbs
        always_pull: true
        tags: base_${{ github.sha }},base_latest
        path: ./docker/base/

    - name: Build docker `fenics` image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: sfbelaine/oss_dbs
        always_pull: true
        tags: fenics19_${{ github.sha }},fenics19_latest
        path: ./docker/fenics19/

    - name: Build docker `platform_test` image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: sfbelaine/oss_dbs
        always_pull: true
        tags: platform_test_${{ github.sha }},platform_test_latest
        target: python_dep

  test_image:
    runs-on: ubuntu-latest
    container:
      image: sfbelaine/oss_dbs:platform_test_latest
      options: --user 0
    needs: [build_test_image]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Run test
      working-directory: OSS_platform
      run: python3 Launcher_OSS_lite.py

  build_deploy_image:
    runs-on: ubuntu-latest
    needs: [build_test_image, test_image]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Build docker `platform` image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: sfbelaine/oss_dbs
        always_pull: true
        tags: platform_${{ github.sha }},platform_latest
