name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_images:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker Base image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: sfbelaine/oss_dbs
        path: docker/base
        always_pull: true
        tags: base_${{ github.sha }}
